name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make script executable
      run: |
        git update-index --chmod=+x build_test.sh
        chmod +x build_test.sh

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build and Run Tests
      id: tests
      run: ./build_test.sh
      continue-on-error: false

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/Test/Testing
        retention-days: 90
