name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: |
        chmod +x build_test.sh
        mkdir -p build
        cd build
        cmake ..

    - name: Build and Run Tests
      run: ./build_test.sh

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4    # Updated to v4
      with:
        name: test-results
        path: build/Test/Testing
        retention-days: 90                # Optional: specify how long to keep artifacts
